# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_photo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
