# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20190531_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.TextField(blank=True),
        ),
    ]
