# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_notification_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.Notification'),
        ),
    ]
