# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0004_auto_20190603_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='area',
            name='notification',
        ),
        migrations.AddField(
            model_name='area',
            name='post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='area',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
