# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20190603_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
