# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0006_area_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('post', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='email',
        ),
        migrations.RemoveField(
            model_name='area',
            name='post',
        ),
        migrations.RemoveField(
            model_name='area',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='area',
            name='title',
        ),
        migrations.AddField(
            model_name='updates',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.Area'),
        ),
        migrations.AddField(
            model_name='updates',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
