# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_auto_20190603_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
